### ISSUE TITLE
Windows executable not building with either py2exe or pyinstaller

### ISSUE THREAD

**Issue by lambsteak** [lambsteak/auto-pixel-canvas#2]
76 INFO: PyInstaller: 3.2.1
76 INFO: Python: 3.6.1
77 INFO: Platform: Windows-10-10.0.14393-SP0
81 INFO: wrote E:\work\auto-pixel-canvas\auto_pixel\auto_pixel.spec
81 INFO: UPX is not available.
82 INFO: Extending PYTHONPATH with paths
['E:\\work\\auto-pixel-canvas\\auto_pixel',
 'E:\\work\\auto-pixel-canvas\\auto_pixel']
82 INFO: checking Analysis
83 INFO: Building Analysis because out00-Analysis.toc is non existent
83 INFO: Initializing module dependency graph...
84 INFO: Initializing module graph hooks...
86 INFO: Analyzing base_library.zip ...
Traceback (most recent call last):
  File "C:\Work\Python\Scripts\pyinstaller-script.py", line 11, in <module>
    load_entry_point('PyInstaller==3.2.1', 'console_scripts', 'pyinstaller')()
  File "c:\work\python\lib\site-packages\PyInstaller\__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\work\python\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\work\python\lib\site-packages\PyInstaller\building\build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\work\python\lib\site-packages\PyInstaller\building\build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "c:\work\python\lib\site-packages\PyInstaller\building\build_main.py", line 212, in __init__
    self.__postinit__()
  File "c:\work\python\lib\site-packages\PyInstaller\building\datastruct.py", line 161, in __postinit__
    self.assemble()
  File "c:\work\python\lib\site-packages\PyInstaller\building\build_main.py", line 317, in assemble
    excludes=self.excludes, user_hook_dirs=self.hookspath)
  File "c:\work\python\lib\site-packages\PyInstaller\depend\analysis.py", line 560, in initialize_modgraph
    graph.import_hook(m)
  File "c:\work\python\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1509, in import_hook
    source_package, target_module_partname, level)
  File "c:\work\python\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1661, in _find_head_package
    target_module_headname, target_package_name, source_package)
  File "c:\work\python\lib\site-packages\PyInstaller\depend\analysis.py", line 209, in _safe_import_module
    module_basename, module_name, parent_package)
  File "c:\work\python\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2048, in _safe_import_module
    module = self.findNode(module_name)
  File "c:\work\python\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1381, in findNode
    m = self._safe_import_hook(name, None, None).pop()
  File "c:\work\python\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2278, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "c:\work\python\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1509, in import_hook
    source_package, target_module_partname, level)
  File "c:\work\python\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1661, in _find_head_package
    target_module_headname, target_package_name, source_package)
  File "c:\work\python\lib\site-packages\PyInstaller\depend\analysis.py", line 209, in _safe_import_module
    module_basename, module_name, parent_package)
  File "c:\work\python\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2077, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "c:\work\python\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2167, in _load_module
    self._scan_code(m, co, co_ast)
  File "c:\work\python\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2585, in _scan_code
    module, module_code_object, is_scanning_imports=False)
  File "c:\work\python\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2831, in _scan_bytecode
    global_attr_name = get_operation_arg_name()
  File "c:\work\python\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2731, in get_operation_arg_name
    return module_code_object.co_names[co_names_index]
IndexError: tuple index out of range

**Comment by lambsteak** [comment]
Issue solved: cx_Freeze has the best support for python3 so I tried it with that and it works like a charm!
